[versions]
activityCompose = "1.10.1"
agp = "8.10.1"
arsclib = "1.3.5"
bcprovJdk18on = "1.80"
coilCompose = "3.1.0"
coilGif = "3.1.0"
coilNetworkOkhttp = "3.1.0"
composeMarkdown = "0.5.7"
fetch2 = "3.4.1"
fetch2okhttp = "3.4.1"
kotlin = "2.0.0"
coreKtx = "1.16.0"
lifecycleRuntimeKtx = "2.8.7"
navigationCompose = "2.8.9"
okhttp = "4.12.0"
ksp = "2.0.0-1.0.22"
datastore = "1.1.4"
plausibleAndroidSdk = "54ea1a1359"
room = "2.7.0"
appcompat = "1.7.0"
coordinatorlayout = "1.3.0"
material = "1.12.0"
rootbeerLib = "0.1.1"
runtimeAndroid = "1.7.8"
timber = "5.0.1"
zipalignJava = "1.2.1"
zipAndroid = "2.2.0"
workRuntimeKtx = "2.10.4"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
arsclib = { module = "io.github.reandroid:ARSCLib", version.ref = "arsclib" }
bcprov-jdk18on = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bcprovJdk18on" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coilGif" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilNetworkOkhttp" }
compose-markdown = { module = "com.github.jeziellago:compose-markdown", version.ref = "composeMarkdown" }
fetch2 = { module = "com.github.tonyofrancis.Fetch:fetch2", version.ref = "fetch2" }
fetch2okhttp = { module = "com.github.tonyofrancis.Fetch:fetch2okhttp", version.ref = "fetch2okhttp" }
plausible-android-sdk = { module = "com.github.Rattlyy:plausible-android-sdk", version.ref = "plausibleAndroidSdk" }
rootbeer-lib = { module = "com.scottyab:rootbeer-lib", version.ref = "rootbeerLib" }
square-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinatorlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
zip-android = { module = "io.github.diamondminer88:zip-android", version.ref = "zipAndroid" }
zipalign-java = { module = "com.github.iyxan23:zipalign-java", version.ref = "zipalignJava" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
